const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL
const API_URL = process.env.NEXT_PUBLIC_API_URL
const API_PATH = process.env.NEXT_PUBLIC_API_PATH
const LOGIN_PATH = process.env.NEXT_PUBLIC_LOGIN_PATH
const USER_PATH = process.env.NEXT_PUBLIC_USER_PATH
const REFRESHTOKEN_PATH = process.env.NEXT_PUBLIC_REFRESHTOKEN_PATH

export {
  BACKEND_URL,
  API_URL,
  API_PATH,
  LOGIN_PATH,
  USER_PATH,
  REFRESHTOKEN_PATH,
}
